spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
server:
  port: 8084
eureka:
  client:
    register-with-eureka: true # register him self at eureka
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
logging:
  level:
    com.renfobackend.gateway: DEBUG
management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: gateway

