spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: etiennedubois
    password: 
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    log-request-details: true
server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security.web: DEBUG
    org.springframework.web: TRACE
    org.apache.http: DEBUG
